### PR TITLE
Add paginationDefaultPage prop to DataTable for setting the initial page number

### PR DESCRIPTION
**Pull request by Lknechtli**
Add a `defaultPage` prop to DataTable.
This is useful when you want to store the page size / number in a url parameter and allow navigating directly to a page in the table.

I think this is what #99 is asking for, but either way it would be very useful to have.

### CODE REVIEW

**Comment by jbetancur** [comment]
Thank you for the PR! I'll have a look at this a little later today.

**Comment by jbetancur** [comment]
Ok, just a few things and I can get this merged in:

* To keep the naming convention can you rename to `paginationDefaultPage`?
* Make sure the tests pass `yarn test`
* Update the README with the new property

**Comment by Lknechtli** [comment]
:+1: I'll have some time in the morning to do it.

**Comment by Lknechtli** [comment]
image
@jbetancur Pushed the fixes

**Comment by allencazar** [comment]
@jbetancur , is there a proper way to control or set the current page?
- wanted to go to last page or any page programmatically. 
- highlight last/new added row.

**Pull request merged**
