### PR TITLE
Fix typo in pagination component options story

### PR DESCRIPTION
**Pull request by yunghog**
## Fix typo in pagination component options story, rowsPerPageText prop description.

- Before fixing
image

- After fixing
image

### CODE REVIEW

**Comment by alexk400** [comment]
Can someone add this feature.  I wanted to have externalise style data 
		....
	var newdest=destination[key];
        if(typeof newdest === 'function') 
        destination[key]=newdest();
	
it should be in merge object inner loop but i dont where in src files.  What it does is that any style entry can be anonymous function , so in that way all styles can be customized.

  color: (opacity=.5) =>  `rgba(255, 255, 255, ${opacity})`
  this allow all kinda logic added to  Table Style object. 
  Any object properties can be function. if it see a function , it calculate and saved the results.
  Let me know if anyone can do this.

 i tested with react-data-table-component-dev.js  ( index.cjs.js obfuscated)
 
 This is the change
 
 function mergeObject(target, source, options) {
    var destination = {};
	if (options.isMergeableObject(target)) {
		getKeys(target).forEach(function(key) {
          	destination[key] = cloneUnlessOtherwiseSpecified(target[key], options);
		});
	}
	getKeys(source).forEach(function(key) {
		if (propertyIsUnsafe(target, key)) {
			return
		}

        var newsource=source[key];
        if(newsource === 'function') 
        source[key]=newsource();

		if (propertyIsOnObject(target, key) && options.isMergeableObject(source[key])) {
			destination[key] = getMergeFunction(key, options)(target[key], source[key], options);
		} else {
			destination[key] = cloneUnlessOtherwiseSpecified(source[key], options);
		}

        var newdest=destination[key];
        if(typeof newdest === 'function') 
        {
            //convert anonymous function to result string
            destination[key]=newdest();
        }
 
	});
	return destination
}

**Comment by alexk400** [comment]
I have another issue and i want to add Plus button. But its render twice. I want it to render along with table. How do i make it render. Why not datatable allow user to have some custom control there? 
I have many plans in that corner. Server scrollable control  checkbox for checkbox screens , al expand and others.
[add button draw issue.webm](https://user-images.githubusercontent.com/8467283/225772601-10ad2c67-7d08-49a7-b7b2-f6219114d1e1.webm)

**Comment by sadashivm** [comment]
Hello @yunghog , how to create a new issue?
 I'm unable to see "create issue" button anywhere.
 Hence I've added my issue inside below link,
 
[https://github.com/jbetancur/react-data-table-component/pull/1140](https://github.com/jbetancur/react-data-table-component/pull/1140)

Please check the above URL.

Can you please tell me how to create a new issue here?

**Comment by sadashivm** [comment]
One more issue which is added here,
[https://github.com/jbetancur/react-data-table-component/pull/1037](https://github.com/jbetancur/react-data-table-component/pull/1037)

**Pull request merged**
