### PR TITLE
Feature/pagination position

### PR DESCRIPTION
**Pull request by shahidsarker**
Added `paginationPosition` property to allow positioning of Pagination component at top, bottom, or both.

Related to #551, #641, #678

### CODE REVIEW

**Comment by shahidsarker** [comment]
@jbetancur friendly ping!

**Comment by jbetancur** [comment]
Thanks for the PR! @shahidsarker - I have not had some time to look at this but will do as soon as I can.

**Comment by shahidsarker** [comment]
@jbetancur another friendly ping as this PR's gone stale

**Comment by arthurbrener** [comment]
Hi, any update on this matter? Would be really good to have this feature

**Comment by akaufman3** [comment]
Seconding @arthurbrener - this would be a great feature - any plan on this being merged soon?

**Comment by kvndevils** [comment]
One more friendly ping. Would be awesome to have this one. Thx!

**Pull request closed without merging**
