### PR TITLE
Fix styled component errors 2

### PR DESCRIPTION
**Pull request by jessewriter**
building off off [HendrikPetertje](https://github.com/HendrikPetertje) PR i also removed the final styled component errors for 'right' and 'sortActive'

### CODE REVIEW

**Comment by jessewriter** [comment]
not sure why there are netlify errors as this work just fine in my project and all the styled warnings are gone from my console.  we have many different tables and no errors :/

**Comment by jessewriter** [comment]
ok i see that my $right fix did not work and those columns are still left oriented.  error is gone but intended effect is wrong will investigate tmro

**Comment by jessewriter** [comment]
> heya @jessewriter, noticing the error you are trying to fix too now :) Do you want me to help you out so we can get this pull over the line?

yes sir, we are running this fork successfully but i never did update the unit tests.  right and sortActive both cause issues and we fixed.  can't remember if there were any more but 0 errors on our side.  only unit tests remain

**Comment by amirfaisalz** [comment]
any update on this?
the issue still persist

**Comment by SamuelDowse** [comment]
The issue is with styled-components version 6.x and above, the issue does not exist on styled-components version 5.x

This library needs updating to support styled-components version 6.x

**Comment by allan-vera** [comment]
Are there any suppression suggestions besides installing the correct version of style-components (for projects that dont use SC)

**Pull request closed without merging**
