### PR TITLE
add last affected rows to state.

### PR DESCRIPTION
**Pull request by ahmed-abdelmotey**
This will enable users to handle actions depending on the selection of the rows.

### CODE REVIEW

**Comment by ahmed-abdelmotey** [comment]
Please letme know if there is some changes needed before I update the test files assertions if needed.

**Comment by jbetancur** [comment]
Thanks for the PR! I’ve been a bit busy so have not had a chance to review. I’ll spend some time on it this week.

Off the top of my head would it be easier to just have a new callback that gives you the current row that was selected?

**Comment by jbetancur** [comment]
@ahmed-abdelmotey can you provide an example of his this is used in practice?

**Comment by ahmed-abdelmotey** [comment]
Thank you for your patience, 


the scenario is: 
if you have an array of data and a property is used to determine if the row is selected or no, once you update the selection in the table this should reflect on the state of the parent component, there is no way to find out the affected row unless you loop over all the items to determine which one was selected or un selected

**Pull request closed without merging**
