### PR TITLE
Add possibility to opt-in for dynamic props for each checkbox instance.

### PR DESCRIPTION
**Pull request by lautiab**
Relates to [issue 1007](https://github.com/jbetancur/react-data-table-component/issues/1007)

### CODE REVIEW

**Comment by lautiab** [comment]
Hey @jbetancur would you mind taking a look into this one? Thanks!

**Comment by jbetancur** [comment]
@lautiab Not sure how I feel about this name `rowOnlyCheckboxProps` is should probably be named something like `selectableRowComponentProps`. This is a bit long, but it fits with the current naming convention. Note that in a version 8 of RDT I will be moving most of these props into an `options` prop. so this would in theory become `options.selectable.rowComponentProps`.

Also please add documentation to the storybook examples

**Comment by jbetancur** [comment]
I wonder if another option could be to have `selectableRowsComponentProps` accept either object or callback format. This way we do not add a new property, but allow the you to opt into either format.

**Comment by jbetancur** [comment]
For example,

`selectableRowsComponentProps={row => ({ 'aria-label': 'Select row ${row.title}', className: 'padding-1', etc... })}`

**Comment by lautiab** [comment]
That was my first approach, but given how the prop is used for the heading checkbox too (select-all button), calling the function with row component as argument was resulting in undesired behavior for the header component props. Let me re-check those drawbacks so I can be more literal on my explanation, don't have the example right now, just recalling what I remember from the day I'd worked on it.

**Pull request closed without merging**
