### PR TITLE
Added new prop persistCurrentPageOnSort for paginationServerOptions 

### PR DESCRIPTION
**Pull request by vijicode**
Added new prop persistCurrentPageOnSort for paginationServerOptions to keep currentPage on sort_change event.

### CODE REVIEW

**Comment by vijicode** [comment]
Could you please take a look at this proposed change ? @jbetancur   Thank you so much.

**Comment by ninjaengineers** [comment]
@jbetancur any update on this?

**Comment by jbetancur** [comment]
Sorry for the delay, I’ve tagged this into the next version as I’m currently migrating the code base to typescript. So, I’ve been a bit focused on that. I need sometime to test this scenario and a see how it integrates with the future RDT design.

Can you step me through some scenarios as to what this changes? Are we sure this does not break anything pagination related?

**Comment by vijicode** [comment]
I have tried to add a new prop called "persistCurrentPageOnSort" ( false by default). If the developer is implementing server-side pagination and No server-side sorting, then it means that the sorting will depend on the per-page sorting with whatever table data is on that particular page. Therefore , to reset the page number back to 1 will not be suitable. Hence I added a check, if pagination && paginationServer && persistCurrentPageOnSort then keep the page number same as the one in the current state.
Example scenario:
server-side-pagination - returns 5 pages
server-side-sorting - not implemented
UX - user navigates to page 4 and clicks sort button on any column
UX - user will stay on page 4, contents of page4 will be sorted 
( Without fix, user will get sent to page 1 )

Thanks.

**Comment by emanuallan** [comment]
Was this integrated elsewhere because this would be useful!

**Comment by AhmadRaza09** [comment]
Please merged this issue. this is helpful

**Comment by AhmadRaza09** [comment]
Please merged this issue. this is helpful

@jbetancur

**Comment by GregoryInnovo** [comment]
This change is very important in some use cases

**Pull request closed without merging**
