### PR TITLE
Allow custom row container as optional

### PR DESCRIPTION
**Pull request by ashotmark**
## Why

In some cases(in our project), we need row to be link, so that users are able to open in new tab or same tab by clicking row as their desired.
In my checking all props, realized that's impossible.

## What

I added new `renderRow` prop to `DataTable` as optional.
if `renderRow` is missing, `DataTable` will work as currently.
else if `renderRow` is present, this will be invoked to render rows for table.

## Example

```
const renderRow = (row, rowContent) => <a key={row.id} href="/test">{rowContent}</a>
<DataTable ...existingProps renderRow={renderRow} />
```

### CODE REVIEW

**Comment by ashotmark** [comment]
@nickgirardo  Thanks for comment
I created storybook for this usages, so that you can see how to use on your component.
in my case, I installed this package from  current `github` repo because we can not wait until this PR gets approved and merged 👍 
here is storybook: `stories/DataTable/RowLink.stories.js`

**Comment by SupraSmooth** [comment]
I would love to have that feature! Please run `eslint --fix \"**/*.*\"` and `prettier --write \"**/*.*\"` commands in your project directory to fix the code style errors. Run `npm run lint` before your push to verify your code.

**Comment by ashotmark** [comment]
Thanks @SupraSmooth , I added it towork list, will fix and push today.

**Comment by ashotmark** [comment]
fixed eslint and prettier issue. now all checks are passed :100:

**Comment by paulStoia** [comment]
Great job with this feature! When it will be merged and released? It is very useful and critical in some cases because it allows to control how a row is rendered, hence you can add much more operations in the table. We really need this!

**Comment by samuelhalim1** [comment]
any updates?

**Comment by Niwilai** [comment]
@jbetancur any chance we could get this in? It would be useful for us. Ty

**Pull request closed without merging**
