### PR TITLE
hint: maxWidth under 100px won't work by itself

### PR DESCRIPTION
**Pull request by cliffordp**
As evidenced by https://codesandbox.io/s/react-data-table-cannot-set-maxwidth-less-than-100px-without-also-minwidth-uj5kp?file=/src/index.js

### CODE REVIEW

**Comment by cliffordp** [comment]
@jbetancur actually, in testing this with _multiple 20px columns in a row,_ the column titles imploded/jumbled up on top of each other. Not sure if that's a bug to be fixed or if **minWidth** (in addition to this PR) should state that it shouldn't ever be less than 100px or bad things could happen.

**Comment by jbetancur** [comment]
@cliffordp This is a challenge in building a table library, keeping some control over the min-width of columns while not allow things to break when people try to break things 😉 . I think it's good to call it out on the README so thanks for the PR! 😄 

I think we can work it a litle differently:

**Comment by jbetancur** [comment]
I think we can work it a little differently to some variation of:

*Note: minWidth defaults to 100px. If you require a column smaller than 100px `minWidth` can be overridden using a static `width` or setting a `minWidth` lower than 100px*

**Comment by cliffordp** [comment]
@jbetancur which attribute do you want that comment on - maxWidth?

**Comment by cliffordp** [comment]
@jbetancur please reply to my prior comment or confirm that closing this is your preference.

**Comment by jbetancur** [comment]
Sorry @cliffordp I must have missed this. `minWidth could be re-written as it overrides the default 100px if you want to resubmit a PR

**Pull request closed without merging**
