### PR TITLE
Fix unrecognized prop errors in React

### PR DESCRIPTION
**Pull request by HendrikPetertje**
React does not like receiving object props that don't match any HTML spec. Styled components is dealing with this problem by prefixing all non-standard properties one might want to send in with dollar signs as `$transientProps`

You can read more about it here:
https://styled-components.com/docs/api#transient-props

This fix gets rid of these kind of errors (that the test suite in my project is tripping over since we updated react and styled-components):
image

### CODE REVIEW

**Comment by HendrikPetertje** [comment]
wow that's really fancy, deploying everything to a storybook and all!
hats off on that one!

**Comment by medram** [comment]
I'm having many errors on the browser console too for the same cause reason, please fixed soon :D.

**Comment by loursbourg** [comment]
The changes made in this PR has definitely brought some improvements, the browser console is showing warnings related to incorrect prop naming. For instance:

```
Warning: Received `true` for a non-boolean attribute `responsive`.
```

and

```
Warning: React does not recognize the `fixedHeader` prop on a DOM element
```

Those errors are really cluttering the console. Please, merge.

**Comment by loursbourg** [comment]
Seems like this package is no longer maintained…

**Comment by jessewriter** [comment]
is there a way to hide these warnings until this is merged?  makes my console a mess.  thanks for the update Hendrik

**Comment by jessewriter** [comment]
this seems like good advice on how to consume the prop and not pass it forward https://legacy.reactjs.org/warnings/unknown-prop.html

**Comment by medram** [comment]
it's been a year and this repo/project is frozen, please can anyone fork this repo and keep the project going/updated?

**Review by jessewriter — APPROVED** [review]

**Comment by oancius** [comment]
@jessewriter Thanks for reviewing this PR! Do you know if it will be merged and a new version will be released soon?

**Comment by jessewriter** [comment]
@oancius i have no read write authority on this repo.  i did pull this commit down locally and published to our company artifactory and it is an improvement with many less warnings.  I created a PR off of this fixing the remaining warnings.  Unfortunately i did not fix the jest tests so build fails ugh :/  (work in progress) so we might be on our own here to create our own artifact with the fix

**Comment by oancius** [comment]
> @oancius i have no read write authority on this repo. i did pull this commit down locally and published to our company artifactory and it is an improvement with many less warnings. I created a PR off of this fixing the remaining warnings. Unfortunately i did not fix the jest tests so build fails ugh :/ (work in progress) so we might be on our own here to create our own artifact with the fix

got it! thanks for the quick reply tho! 🙌🏼

**Comment by HendrikPetertje** [comment]
I don't really have the bandwidth myself to become the sole maintainer for this plugin and I can not guarantee that I'll be working with react for the next 10 years either :), but I'll give it a try I guess, becuase I need this plugin for a bunch of different projects.

So, I'll reach out to @jbetancur (the original maintainer) and:
- Ask him to update the README of this repo to call for new maintainers
- Inform him that I'll publish a semi-maintained fork of the plugin to npm/yarn in the next few days unless he himself appoints someone else (or himself) to pick up the maintenance of the plugin.

**Comment by jbetancur** [comment]
@HendrikPetertje As you, my very limited bandwidth has kept me from maintaining this project as I once did. Managing all the issues and feature asks have become challenging because this project was originally intended to be a simple table library and instead grew to something more comprehensive. I have been struggling to find a co maintainer to help out as there are many needed improvements, refactors, React 18, and bug fixes that need to be made or considered. But in the meantime I am open to having someone else drive for a bit to squash some of the bugs and because the community has come to depend on this project.

**Comment by jbetancur** [comment]
version 7.5.4 with this has been published

**Comment by loursbourg** [comment]
> version 7.5.4 with this has been published

great, i've been looking forward to this

**Comment by AgusRdz** [comment]
I solved doing this

```js
import { styled } from 'styled-components'

export const WidthBox = styled.div`
  width: ${(props) => props.$width || 'auto'};
  min-width: ${(props) => props.$minWidth || 'auto'};
  max-width: ${(props) => props.$maxWidth || 'none'};
`
```

and on the columns definition this

```js
... other columns
{
        id: 'total',
        name: 'Total',
        sortable: true,
        sortField: 'total',
        cell: ({ total }) => (
          <WidthBox $minWidth="102px">{total}</WidthBox>
        )
},
```

**Pull request merged**
