### PR TITLE
Add custom texts to pagination component

### PR DESCRIPTION
**Pull request by metabaronespinosa**
Just added the possibility to pass custom texts to pagination component

### CODE REVIEW

**Comment by hiukky** [comment]
@metabaronespinosa your commit reminds me of my ..  : )

**Comment by Lknechtli** [comment]
I think it might be better just to add a localizationText prop. Passing a separate prop for each string seems slightly silly when you consider that most applications that support localization store the strings in a separate file.
Doing something like this seems a bit silly:
```javascript
import L10nJson from "L10n.json";
const { rowsPerPageText, ofText, ...otherTextFieldsAsProps} = L10nJson;
const LocalizedDataTable= (...props) => <DataTable {...props} rowsPerPageText={rowsPerPageText} ofText={ofText} {...otherTextFieldsAsProps} />;
```
when you can just do
```javascript
import L10nJson from "L10n.json";
const LocalizedDataTable= (...props) => <DataTable {...props} localizationText={L10nJson} />;
```

**Comment by hiukky** [comment]
@Lknechtli yea!  I had done this in a first case, but I was looking for another way to improve it!  Your idea is cool ..

**Comment by jbetancur** [comment]
I was planning on adding a new prop `paginationComponentOptions` that takes an object of values that can be used to override the default pagination component as well as used for custom component development when you want to provide a hook.

e.g.
```
onChangeRowsPerPage={ rowsPerPageText: 'Rows per Page' }
```

**Comment by hiukky** [comment]
@jbetancur 
Very good! here are but a few options we need hehe! : )
image

**Comment by jbetancur** [comment]
@hiukky 1.5.4 now has `paginationComponentOptions`. As for progress, noData and expander you can just use: progressComponent, noDataComponent, and expandableRowsComponent respectively. These props take either a string or component:

```
class MyComponent extends Component {
  render() { 
    return (
      <DataTable
        title="Arnold Movies"
        columns={columns}
        data={data}
        progressComponent="Un Momento"
        noDataComponent="Nada"
        expandableRowsComponent="actually, you would always use a custom component here"
        pagination
        paginationComponentOptions={{ rowsPerPageText: 'Filas por pagina', rangeSeparatorText: 'de' }}
      />
    )
  }
);
```

**Comment by hiukky** [comment]
@jbetancur 
Good in both cases of progressComponent and expandableRowsComponent will not go right because here 
https://github.com/jbetancur/react-data-table-component/blob/master/src/DataTable/propTypes.js#L101-L103 
you are passing an element, then the user would also have to pass an element and if it does not do this an error will be triggered against the defined PropTypes! what I had done was left just the string there and put the elements in the main file rendering them ... and also ends up not having a standardization since some not very experienced user may think that if you put progressText as in `paginationComponentOptions = {rangeSeparatorText : '....'} `will work do not you think?

I think defining a prop getting all the string used would be more interesting than dividing by categories .. pagination ..body ..head `DataTableText = {prop: '...', prop2: '...'}` For example

**Comment by jbetancur** [comment]
You are correct about the prop type not accepting string for expandableComponet, but Expandable rows does not need translation or options as it is literally meant for you to pass in a custom component 100% of the time.

progressComponent accepts a string however, here I would expect someone to pass a progress component but you can pass text just the same. 

For pagination I think as long as the api is documented clearly - which it is on the readme and storyboard and we have examples it should work. I’m not a fan of managing language in the library, but for pagination I provided the hooks to do so since it’s a bit of an outlier. 

Hope that helps but 1.5.5 which I released today has the paginationOptions for you to use

**Comment by metabaronespinosa** [comment]
Hey, thank you very much for the last release, it totally solves what I wanted to reach

**Comment by dinizime** [comment]
Sorry for re-opening. But how about localization in Selectable Rows? (... item selected)

**Comment by jbetancur** [comment]
@dinizime I was thinking about this the other day. I'll open a separate issue for this, though I don't think it will be as easy as adding localization. Need to re-thing the context menu a bit

**Pull request closed without merging**
